Update Composer Packages

diff --git a/cake3/rd_cake/vendor/composer/composer/bin/composer b/cake3/rd_cake/vendor/composer/composer/bin/composer
--- a/cake3/rd_cake/vendor/composer/composer/bin/composer
+++ b/cake3/rd_cake/vendor/composer/composer/bin/composer
@@ -5,12 +5,18 @@ if (PHP_SAPI !== 'cli' && PHP_SAPI !== 'phpdbg') {
     echo 'Warning: Composer should be invoked via the CLI version of PHP, not the '.PHP_SAPI.' SAPI'.PHP_EOL;
 }
 
+if (PHP_VERSION_ID < 70205) {
+    echo 'Composer 2.3.0 dropped support for PHP <7.2.5 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
+    exit(1);
+}
+
 setlocale(LC_ALL, 'C');
 require __DIR__.'/../src/bootstrap.php';
 
 use Composer\Console\Application;
 use Composer\XdebugHandler\XdebugHandler;
 use Composer\Util\Platform;
+use Composer\Util\ErrorHandler;
 
 error_reporting(-1);
 
@@ -21,6 +27,12 @@ unset($xdebug);
 
 if (defined('HHVM_VERSION') && version_compare(HHVM_VERSION, '4.0', '>=')) {
     echo 'HHVM 4.0 has dropped support for Composer, please use PHP instead. Aborting.'.PHP_EOL;
+    exit(1);
+}
+if (!extension_loaded('iconv') && !extension_loaded('mbstring')) {
+    echo 'The iconv OR mbstring extension is required and both are missing.'
+        .PHP_EOL.'Install either of them or recompile php without --disable-iconv.'
+        .PHP_EOL.'Aborting.'.PHP_EOL;
     exit(1);
 }
 
@@ -58,7 +70,19 @@ if (function_exists('ini_set')) {
     unset($memoryLimit);
 }
 
+// Workaround PHP bug on Windows where env vars containing Unicode chars are mangled in $_SERVER
+// see https://github.com/php/php-src/issues/7896
+if (PHP_VERSION_ID >= 70113 && (PHP_VERSION_ID < 80016 || (PHP_VERSION_ID >= 80100 && PHP_VERSION_ID < 80103)) && Platform::isWindows()) {
+    foreach ($_SERVER as $serverVar => $serverVal) {
+        if (($serverVal = getenv($serverVar)) !== false) {
+            $_SERVER[$serverVar] = $serverVal;
+        }
+    }
+}
+
 Platform::putEnv('COMPOSER_BINARY', realpath($_SERVER['argv'][0]));
+
+ErrorHandler::register();
 
 // run the command application
 $application = new Application();
